# Importing Data

In [1]:
import pandas as pd

In [2]:
health=pd.read_csv('C:\\Users\\merug\\Desktop\\Market Fit Research for Air Purifier\\Dataful_Datasets\\master-data-state-district-and-disease-wise-cases-and-death-reported-due-to-outbreak-of-diseases-as-per-weekly-reports-under-idsp.csv',encoding="latin1")

In [3]:
health.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26553 entries, 0 to 26552
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   year                    26553 non-null  int64
 1   week                    26553 non-null  int64
 2   outbreak_starting_date  26546 non-null  object
 3   reporting_date          18368 non-null  object
 4   state                   26518 non-null  object
 5   district                26503 non-null  object
 6   disease_illness_name    26552 non-null  object
 7   status                  26553 non-null  object
 8   cases                   26544 non-null  float64
 9   deaths                  26544 non-null  float64
 10  unit                    26553 non-null  object
 11  note                    43 non-null     object
dtypes: float64(2), int64(2), object(8)
memory usage: 2.4+ MB

In [4]:
health=health.drop(columns=['unit','note'])

In [5]:
health.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26553 entries, 0 to 26552
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   year                    26553 non-null  int64
 1   week                    26553 non-null  int64
 2   outbreak_starting_date  26546 non-null  object
 3   reporting_date          18368 non-null  object
 4   state                   26518 non-null  object
 5   district                26503 non-null  object
 6   disease_illness_name    26552 non-null  object
 7   status                  26553 non-null  object
 8   cases                   26544 non-null  float64
 9   deaths                  26544 non-null  float64
dtypes: float64(2), int64(2), object(6)
memory usage: 2.0+ MB

In [6]:
health.columns

Index(['year', 'week', 'outbreak_starting_date', 'reporting_date', 'state',
       'district', 'disease_illness_name', 'status', 'cases', 'deaths'],
      dtype='object')

In [7]:
health.head(10)

,year,week,outbreak_starting_date,reporting_date,state,district,disease_illness_name,status,cases,deaths
0,2025,14,05-04-2025,05-04-2025,Assam,Biswanath,Food Poisoning,Reported,18.0,0.0
1,2025,14,03-04-2025,04-04-2025,Bihar,Aurangabad,Fever with Rash,Reported,21.0,0.0
2,2025,14,31-03-2025,04-04-2025,Bihar,Madhubani,Chickenpox,Reported,14.0,0.0
3,2025,14,03-04-2025,04-04-2025,Gujarat,Bhavnagar,Food Poisoning,Reported,20.0,0.0
4,2025,14,01-04-2025,01-04-2025,Gujarat,Vadodara,Acute Diarrheal Disease,Reported,20.0,0.0
5,2025,14,31-03-2025,31-03-2025,Haryana,Yamunanagar,Food Poisoning,Reported,104.0,0.0
6,2025,14,05-04-2025,05-04-2025,Jharkhand,East Singhbum,Chickenpox,Reported,8.0,0.0
7,2025,14,03-04-2025,03-04-2025,Jharkhand,Giridih,Chickenpox,Reported,13.0,0.0
8,2025,14,04-04-2025,04-04-2025,Karnataka,Chikballapur,Hepatitis A,Reported,8.0,0.0
9,2025,14,31-03-2025,04-04-2025,Kerala,Kottayam,Food Poisoning,Reported,22.0,0.0

In [8]:
health.isnull().sum()

year                         0
week                         0
outbreak_starting_date       7
reporting_date            8185
state                       35
district                    50
disease_illness_name         1
status                       0
cases                        9
deaths                       9
dtype: int64

In [9]:
health['year'].tail()

26548    2009
26549    2009
26550    2009
26551    2009
26552    2009
Name: year, dtype: int64

In [10]:
print(health['year'].max(),health['year'].min())

2025 2009

In [11]:
health['year'].isnull().sum()

np.int64(0)

In [12]:
health['week'].tail()

26548    25
26549    25
26550    25
26551    25
26552     9
Name: week, dtype: int64

In [13]:
health['week'].isnull().sum()

np.int64(0)

# handling missing values

In [14]:
health['outbreak_starting_date'].isnull().sum()

np.int64(7)

In [15]:
health['outbreak_starting_date']

0        05-04-2025
1        03-04-2025
2        31-03-2025
3        03-04-2025
4        01-04-2025
            ...
26548    20-06-2009
26549    13-06-2009
26550    07-06-2009
26551    04-06-2009
26552    25-05-2009
Name: outbreak_starting_date, Length: 26553, dtype: object

In [16]:
health['outbreak_starting_date'] = pd.to_datetime(
    health['outbreak_starting_date'],
    dayfirst=True,
    errors='coerce'
)

In [17]:
health[health['outbreak_starting_date'].isna()]

,year,week,outbreak_starting_date,reporting_date,state,district,disease_illness_name,status,cases,deaths
10669,2018,15,NaT,NaN,Uttar Pradesh,Budaun,Measles,Reported Late,NaN,NaN
10670,2018,15,NaT,NaN,Uttar Pradesh,Rae Bareli,Measles,Reported Late,NaN,NaN
10671,2018,15,NaT,NaN,Uttar Pradesh,Siddharth Nagar,Measles,Reported Late,NaN,NaN
12446,2017,13,NaT,NaN,Odisha,Koraput,Anthrax,Previous Week Follow up,7.0,0.0
16021,2015,39,NaT,NaN,Arunachal Pradesh,Papum Pare,Dengue,Previous Week Follow up,43.0,0.0
22044,2012,26,NaT,NaN,Assam,Dibrugarh,Japanese Encephalitis,Reported Late,56.0,7.0
25165,2010,37,NaT,NaN,Uttarakhand,Champawat,Measles,Reported Late,250.0,4.0

In [18]:
health['outbreak_starting_date'].isna().sum()

np.int64(7)

In [19]:
health['state'].isnull().sum()

np.int64(35)

In [20]:
health['state'].value_counts()

state
Maharashtra                                 2679
Karnataka                                   2598
Kerala                                      1963
Tamil Nadu                                  1788
West Bengal                                 1687
Madhya Pradesh                              1621
Bihar                                       1605
Assam                                       1468
Gujarat                                     1441
Uttar Pradesh                               1428
Odisha                                      1380
Jharkhand                                    981
Chhattisgarh                                 871
Andhra Pradesh                               861
Jammu and Kashmir                            660
Rajasthan                                    659
Punjab                                       561
Haryana                                      313
Uttarakhand                                  309
Arunachal Pradesh                            281
Telangana                                    255
Meghalaya                                    196
Himachal Pradesh                             178
Manipur                                      104
Delhi                                         80
Tripura                                       78
Puducherry                                    76
Mizoram                                       74
Dadra and Nagar Haveli                        68
Nagaland                                      63
Goa                                           55
Chandigarh                                    51
Sikkim                                        37
Daman and Diu                                 15
Lakshadweep                                   11
Andaman and Nicobar Islands                    9
Dadra and Nagar Haveli and Daman and Diu       4
Ladakh                                         4
Madhya                                         2
Tamil nadu                                     2
Uttar                                          1
Arunachal                                      1
Name: count, dtype: int64

In [21]:
health['state']=health['state'].str.lower()
health['state']=health['state'].str.title()

In [22]:
health['state'] = health['state'].replace({'Daman And Diu':'Dadra And Nagar Haveli And Daman And Diu',
'Dadra And Nagar Haveli':'Dadra And Nagar Haveli And Daman And Diu'} )

In [23]:
health['state'] = health['state'].replace({'Arunachal':'Arunachal Pradesh','Madhya':'Madhya Pradesh','Uttar':'Uttar Pradesh'})

In [24]:
health['state'].unique()

array(['Assam', 'Bihar', 'Gujarat', 'Haryana', 'Jharkhand', 'Karnataka',
       'Kerala', 'Madhya Pradesh', 'Meghalaya', 'Odisha', 'Puducherry',
       'Tamil Nadu', 'Uttarakhand', 'West Bengal', 'Manipur',
       'Uttar Pradesh', 'Chhattisgarh', 'Jammu And Kashmir',
       'Andhra Pradesh', 'Maharashtra', 'Sikkim', 'Nagaland', 'Punjab',
       'Rajasthan', 'Tripura', 'Mizoram', 'Goa', 'Arunachal Pradesh',
       'Dadra And Nagar Haveli And Daman And Diu', 'Himachal Pradesh',
       'Telangana', 'Andaman And Nicobar Islands', 'Ladakh', 'Chandigarh',
       'Delhi', 'Lakshadweep', nan], dtype=object)

In [25]:
health['state']=health['state'].fillna('Unknown')

In [26]:
health['district'].describe()

count        26503
unique         951
top       Tumakuru
freq           302
Name: district, dtype: object

In [27]:
health['district']=health['district'].str.lower()
health['district']=health['district'].str.title()
health['district']=health['district'].str.strip()

In [28]:
health['district'] =( health['district'].str.split().str.join(" "))

In [29]:
health['district'].isna().sum()
health['district'].value_counts().head()

district
Tumakuru      302
Ernakulam     273
Malappuram    207
Palakkad      179
Thane         174
Name: count, dtype: int64

In [30]:
health['district']=health['district'].fillna("Unknown")

In [31]:
health['district']=health['district'].replace({'badaun':'Budaun','Baudaun':'Budaun','Thiruvallur':'Tiruvallur'})

In [32]:
health['district'].unique()

array(['Biswanath', 'Aurangabad', 'Madhubani', 'Bhavnagar', 'Vadodara',
       'Yamunanagar', 'East Singhbum', 'Giridih', 'Chikballapur',
       'Kottayam', 'Palakkad', 'Pathanamthitta', 'Thrissur', 'Rewa',
       'North Garo Hills', 'West Jaintia Hills', 'Anugul', 'Bhadrak',
       'Mayurbhanj', 'Sambalpur', 'Pondicherry', 'Erode', 'Kallakurichi',
       'Sivaganga', 'Tiruvallur', 'Tiruchirappalli', 'Virudhunagar',
       'Dehradun', 'Haridwar', 'Purba Barshaman', 'Purbi Champaran',
       'Churachandpur', 'Koraput', 'Agra', 'Jorhat', 'Lakhimpur',
       'Sitamarhi', 'Raipur', 'Anand', 'Kurukshetra', 'Ganderbal',
       'Kulgam', 'Bokaro', 'Dumka', 'East Singhbhum', 'Khunti', 'Ranchi',
       'West Singhbhum', 'Ernakulam', 'Idukki', 'Kannur', 'Kozhikode',
       'Wayanad', 'Damoh', 'Narsinghpur', 'Khordha', 'Coimbatore',
       'Dharmapuri', 'Dindigul', 'Kanniyakumari', 'Theni', 'Hooghly',
       'Guntur', 'Bilaspur', 'Shivpuri', 'Ukhrul',
       'South West Garo Hills', 'Bongaigaon', 'Begusarai', 'Ahmedabad',
       'Jamnagar', 'Patan', 'Jammu', 'Sahebganj', 'Chitradurga',
       'Davangere', 'Hassan', 'Mandya', 'Malappuram', 'Kolhapur',
       'Senapati', 'West Khasi Hills', 'Salem', 'Tenkasi',
       '24 Paraganas South', 'Howrah', 'Medinipur East', 'Medinipur West',
       'Purba Bardhaman', 'Tamulpur', 'Bhopal', 'Gyalshing',
       'Parvathipuram Manyam', 'Barpeta', 'Charaideo', 'Hailakandi',
       'Purnia', 'Sabarkantha', 'Badgam', 'Belagavi', 'Datia', 'Dindori',
       'Gwalior', 'Bhandara', 'Jalgaon', 'Dimapur', 'Sri Muktsar Sahib',
       'Jalore', 'Mayiladuthurai', 'Ranipet', 'Tirupathur',
       'South Tripura', 'Paschim Bardhaman', 'Munger', 'Bagalkot',
       'Alappuzha', 'Lawngtlai', 'Malkangiri', 'Nandyal', 'Nagaon',
       'Jehanabad', 'Samastipur', 'Vaishali', 'Dantewada', 'Durg',
       'Surguja', 'Kachchh', 'Panchmahals', 'Latehar', 'Dakshin Kannad',
       'Chhatarpur', 'Latur', 'Nagpur', 'Washim', 'Ganjam', 'Kendujhar',
       'Jaipur', 'Pudukkottai', 'Ramanathapuram', 'Thanjavur', 'Vellore',
       'Mirzapur', 'Birbhum', 'Purulia', 'Konaseema', 'Anuppur',
       'Bhadohi', 'Darrang', 'Chirang', 'Udalguri', 'Majuli', 'Purbi',
       'Dhamtari', 'Kabirdham', 'Narayanpur', 'South Goa', 'Amreli',
       'Baramulla', 'Palamu', 'Hazaribagh', 'Uttar Kannad', 'Vijayapura',
       'Kalaburagi', 'Thiruvananthapuram', 'Kasaragod', 'Kollam',
       'Ratlam', 'Betul', 'Palaghar', 'Sangli', 'South Garo Hills',
       'Namakkal', 'Lalitpur', 'Alipurduar', 'Nadia',
       'Nandamuri Taraka Rama Rao', 'Visakhapatanam',
       'Sri Potti Sriramulu Nellore', 'Upper Siang', 'Nalbari',
       'Kamrup Metro', 'Sonitpur', 'Madhepura', 'Pashchim Champaran',
       'Gandhinagar', 'Koderma', 'Alappuzha West', 'Raisen', 'Dhar',
       'West Garo Hills', 'Jharsuguda', 'Sundargarh', 'Cuttack',
       'Ariyalur', 'Krishnagiri', 'Karur', 'Gonda',
       'Alluri Sitharama Raju', 'Dima Hasao', 'Patna', 'Saran',
       'Kondagaon', 'Dadra And Nagar Haveli', 'Navsari',
       'Devbhumi Dwarka', 'Deoghar', 'Jamtara', 'Shahdol', 'Akola',
       'Amravati', 'Wardha', 'Nanded', 'East Khasi Hills', 'Nabarangpur',
       'Villupuram', 'Moradabad', 'Ambedkar', 'Muzaffarnagar',
       'Gautam Buddha Nagar', 'Tapi', 'Srinagar', 'Doda', 'Dhanbad',
       'Bengaluru Urban', 'Ashoknagar', 'Guna', 'Thane', 'Boudh',
       'Rupnagar', 'Faridkot', 'Bharatpur', 'Madurai', 'Tuticorin',
       'Dibrugarh', 'Golaghat', 'Karimganj', 'Balod', 'Anantnag',
       'Lohardaga', 'Godda', 'Bidar', 'Burhanpur', 'Khargone',
       'East Nimar', 'Pune', 'Nuapada', 'Patiala', 'Nagapattinam',
       'Farrukhabad', 'Vizianagaram', 'East', 'Tinsukia', 'Goalpara',
       'Bharuch', 'Karnal', 'Shopian', 'Garhwa', 'Chatra', 'Palghar',
       'Osmanabad', 'Eastern West Khasi Hills', 'Rayagada',
       'The Nilgiris', 'Champaran', 'Bhagalpur', 'Kupwara', 'Udhampur',
       'Buldhana', 'Dhenkanal', 'Kota', 'Shamli', 'Shravasti',
       '24 Paraganas North', 'Cooch Behar', 'Anakapalli', 'Tirupati',
       'Pakke Kessang', 'Baloda Bazar', 'Gurugram', 'Poonch',
       'Shivamogga Kyasanur', 'Raigad', 'Jajapur', 'Gangtok',
       'Tiruvannamalai', 'Jamui', 'Mahasamund', 'Mahesana', 'Pulwama',
       'Mysuru', 'Sehore', 'Satara', 'Deogarh', 'Balrampur',
       'Sri Sathya Sai', 'Kokrajhar', 'Dhemaji', 'Rajnandgaon',
       'Thiruvananthap Uram', 'Thiruvarur', 'Fatehpur', 'Jaunpur',
       'Kasganj', 'Cachar', 'Janjgir-Champa', 'Mandla', 'Alirajpur',
       'Indore', 'Nandurbar', 'Baleshwar', 'Mathura', 'Y.S.R.', 'Gaya',
       'Bijapur', 'North Goa', 'Junagadh', 'Narmada', 'Nuh', 'Rajauri',
       'Jhabua', 'Gadchiroli', 'Kandhamal', 'Pratapgarh', 'Prayagraj',
       'Katihar', 'Udupi', 'Jabalpur', 'Nayagarh', 'Balangir', 'Bargarh',
       'Chengalpattu', 'West Siang', 'West Kameng', 'Kheda', 'Haveri',
       'Sheopur', 'Panna', 'Sagar', 'Sindhudurg', 'Sirohi',
       'Pauri Garhwal', 'Murshidabad', 'Spsr Nellore', 'Bhojpur',
       'Bemetara', 'Sukma', 'Simdega', 'Tengnoupal', 'Aizawl',
       'Tirunelveli', 'Barabanki', 'Dinajpur Dakshin', 'Maldah', 'Kangra',
       'Chamarajanagara', 'Nashik', 'Parbhani', 'Gajapati', 'Unnao',
       'Meerut', 'Purba', 'Dakshina Kannada', 'Satna', 'Ahmednagar',
       'Chandrapur', 'Nirmal', 'Kishanganj', 'Vijayanagar', 'Ujjain',
       'Morena', 'Puri', 'Udaipur', 'Kumuram Bheem Asifabad', 'Parulia',
       'Palnadu', 'Kanker', 'Dharwad', 'Tumakuru', 'Ballari', 'Singrauli',
       'Noney', 'Imphal West', 'Kanchipuram', 'Suryapet', 'Rae Bareli',
       'Hapur', 'Ntr', 'Marigaon', 'Valsad', 'Surendranagar', 'Surat',
       'Saraikela Kharsawan', 'Raichur', 'Rajgarh', 'Bhind', 'Dhule',
       'South West Khasi Hills', 'Karaikal', 'Firozepur', 'Sikar',
       'Ballia', 'Nainital', 'South Andamans', 'Bandipora', 'Jodhpur',
       'Jalaun', 'Lucknow', 'Bijnor', 'Mungeli', 'Bengaluru Rural',
       'Chhindwara', 'Gondia', 'Sonepur', 'Sangrur', 'Chittoor',
       'Jashpur', 'Beed', 'Fazilka', 'Cuddalore', 'Sonbhadra',
       'Kushi Nagar', 'Namsai', 'Surajpur', 'Hamirpur', 'Noklak', 'Baran',
       'Rajsamand', 'Chennai', 'Pilibhit', 'Eluru', 'Buxar', 'Shimla',
       'Ramban', 'Pakur', 'Saitual', 'Srikakulam', 'Arwal', 'Raigarh',
       'Kathua', 'Umaria', 'Shajapur', 'Harda', 'Barwani', 'Hoshangabad',
       'Hingoli', 'Bishnupur', 'Kalahandi', 'Kakinada', 'Hojai', 'Bastar',
       'Sarangarh Bilaigarh', 'Dohad', 'Leh Ladakh', 'Siddharth Nagar',
       'Papum Pare', 'Bongaigaon, Kokrajhar', 'Seoni', 'Kendrapara',
       'Dungarpur', 'Kaushambi', 'Kurnool', 'Kamrup', 'Gariyaband',
       'Ahmedabad, Amc, Arvalli, Banaskanth, Bharuch, Bhavnagar, Chhotaudepur, Dahod, Devbhumi Dwarka, Gandhinagar, Gir Somnath, Gmc, Jamnagar, Jmc, Kheda, Kutch, Mahisagar, Mahesana, Morbi, Narmada, Panch Mahal, Patan, Porbandar, Rajkot, Rmc, Sabar Kantha, Smc, Surendranagar ,Vadodara, Vmc',
       'Samba', 'Reasi', 'Kamjong', 'Serchhip', 'Auraiya', 'Anantapur',
       'Bongaigaon, Charaideo, Kokrajhar, Lakhimpur, Nalbari, South Salmara Mancachar',
       'Kolar', 'Gadag', 'Vidisha', 'Jalandhar', 'Kapurthala',
       'Ramanathapura M', 'Chandauli', 'Deoria', 'Lakhisarai',
       'Khairgarh Chhuikhadan Gandai', 'Mohla Manpur Ambagarh Chouki',
       'Chikkamagaluru', 'Solapur', 'Kakching', 'Bapatla',
       'Karbi Anglong', 'Gopalganj', 'Korba', 'Sirmaur', 'Yadgir',
       'Mandsaur', 'Balaghat', 'Dewas', 'Katni', 'Yavatmal', 'Jajpur',
       'S.A.S Nagar', 'Ganganagar', 'Kannauj', 'Kushinagar',
       'Rudraprayag', 'Leparada', 'Lohit', 'Banaskantha', 'Fatehabad',
       'Moga', 'North Tripura', 'Tawang', 'Bajali', 'West Karbi Anglong',
       'Morbi', 'Chhotaudepur', 'Arvalli, Mahisagar, Sabar Kantha',
       'Kaithal', 'Mandi', 'Thoubal', 'Ri Bhoi',
       'Shahid Bhagat Singh Nagar', 'Bhilwara', 'Ghaziabad', 'Almora',
       'Daman', 'Kinnaur', 'Shivamogga', 'Banda', 'Mahisagar', 'Jalna',
       'Ludhiana', 'Soreng', 'Ranga Reddy', 'Khowai', 'Longding',
       'Upper Subansiri', 'Dhubri', 'Rajkot', 'Gir Somnath', 'Gumla',
       'Koppal', 'Tikamgarh', 'East Jaintia Hills', 'Annamayya',
       'Tiruppur', 'Nicobars', 'Tonk', 'Gomati', 'Panchkula', 'Bagalkote',
       'Champhai', 'Dausa', 'Gautam Budh Nagar', 'Jhansi',
       'South Salmara Mancachar', 'Ramanagara', 'Mumbai Suburban',
       'Peren', 'Sakti', 'Gurdaspur', 'Pathankot', 'Botad', 'Tumkur',
       'Agar Malwa', 'Jalpaiguri', 'Sabar Kantha', 'Panchmahal', 'Solan',
       'Kodagu', 'Hoshiarpur', 'Ambedkar Nagar', 'Lower Subansiri',
       'Yadadri Bhuvanagiri', 'Unakoti', 'Khagaria', 'Sivasagar',
       'Sheohar', 'Jagatsinghpur', 'Amroha', 'East Kameng', 'Saharsa',
       'Aravalli', 'Perambalur', 'Neemuch', 'East Garo Hills', 'Bahraich',
       'Changlang', 'Faizabad', 'Fatehgarh Sahib', 'Peddapalli',
       'Nandamuri Taraka Rama Rao (Ntr)', 'Baghpat', 'Saharanpur',
       'Supaul', 'Mamit', 'Kolasib', 'Jhalawar', 'Bolangir', 'Hyderabad',
       'Lunglei', 'Jiribam', 'Siwan', 'Visakhapatnam', 'Palwal',
       'Lower Siang', 'Hnahthial', 'Malerkotla', 'Dang', 'Rajouri',
       'Adilabad', 'Trivandrum', 'Longleng', 'Phek', 'Baksa', 'Banka',
       'Kiphire', 'Lower Dibang Valley', 'Rohtas', 'Hardoi', 'Budaun',
       'Chandigarh', 'South Delhi', 'Tamenglong', 'Balasore', 'Dholpur',
       'Kanpur Dehat', 'Jind', 'Wokha', 'Mon', 'Ramgarh', 'Tehri Garhwal',
       'Siddipet', 'Sepahijala', 'Nellore', 'West District', 'Wanaparthy',
       'Amethi', 'Sonipat', 'Bbmp', 'Kheri', 'Niwari', 'Diamond Harbour',
       'Bathinda', 'Pachim Medinipur', 'Maharajganj', 'Yamuna Nagar',
       'Bellary', 'Paschim Medinipur', 'Basirhat Hd', 'Bangalore',
       'Muzaffarpur', 'Basirhat', 'Shri Muktsar Sahib',
       'North 24 Paraganas', 'South 24 Paraganas', 'Jangir', 'Subarnapur',
       'Anjaw', 'Dhamatari', 'Narayanpet', 'Uttar Dinajpur', 'Nalanda',
       'Sholapur', 'Dhumka', 'Angul', 'Unknown', 'Pithoragarh', 'Alwar',
       'Panipat', 'Kohlapur', 'Jahanabad', 'Mau', 'Chamoli', 'Una',
       'Nagapatinam', 'Jangoan', 'Medak', 'West', 'Vikarabad', 'Khammam',
       'Udham Singh Nagar', 'Warangal', 'Sitapur', 'Keonjhar',
       'Chitrakoot', 'Aizawl West', 'Mansa', 'Jogulamba Gadwal',
       'Kra Daadi', 'Dhaar', 'Ghazipur', 'Chota Udaipur', 'Tuensang',
       'Kamle', 'Sant Ravi Das Nagar', 'Nalgonda', 'Bikaner',
       'Thoothukudi', 'Krishna', 'Pali', 'Sri Ganganagar', 'Bardhaman',
       'Nawanshahr', 'Roopnagar', 'Jagtial', 'Mahabubabad', 'Hanumakonda',
       'Burdhawan', 'Thiruvallore', 'Thiruvallore (Poonamallee)',
       'Karimnagar', 'Thirupathur', 'Uttarkashi', 'Kamareddy',
       'Firozabad', 'Gorakhpur', 'Azamgarh', 'Bareilly', 'Mainpuri',
       'Champawat', 'Panchsheel Nagar',
       'Multiple Districts: Bongaigaon, Darrang, Lakhimpur, Marigaon, Nagaon, Udalguri',
       'Badwani', 'Jhargram', 'Karad', 'Faridabad', 'Nawarangpur',
       'Purba Medinipur', 'Prakasam', 'Nimach', 'West Godavari',
       'West Champaran', 'Ratnagiri', 'Sidhi', 'Lepa Rada', 'Kumey',
       'Mewat', 'Kurung Kumey', 'Kutch', 'Dibang Valley', 'East Sigtan',
       'Bankura', 'Jaintia Hills', 'Delhi', 'South West', 'Ladakh',
       'Barnala', 'Ajmer', 'Warangal Urban', 'Midnapore West', 'Mahoba',
       'Nizamabad', 'Jhajhar', 'Amritsar', 'Nagarkurnool', 'Sirsa',
       'South', 'Muktsar', 'Sangareddy', 'Subansiri', 'Bhabhua',
       'Aizawl East', 'Kohima', 'Araria', 'Ambala', 'Andaman',
       'Sawai Madhopur', 'Kullu', 'East Imphal',
       'West, Churachandpur, Kakching, Senapati And Bishnupur',
       'Puducherry And Karaikal', 'Kawardha', 'Shi Yomi', 'Daman And Diu',
       'Sant Kabir Nagar', 'South Sikkim', 'Mahabubnagar',
       'East Godavari', 'Sheikhpura', 'Tarn Taran', 'Siang', 'East Siang',
       'Tezu', 'Dahod', 'Mahe', 'Medchal Malkajgiri', 'North',
       'Hyderabad Rural', 'Aligarh', 'Multiple Districts', 'Nawada',
       'Mokokchung', 'Maharajaganj', 'Midnapore East', 'Tirap',
       'West Tripura', 'Mumbai', 'Goapalganj', 'Zunheboto',
       'Lakhimpur Kheri', 'Botal', 'Dev Bhumi Dwarka', 'South East',
       'Rampurhat', 'Banswara', 'Chittapur', 'Jhunjhunu', 'Yanam',
       'Jayashankar Bhupalpally', 'Porbandar', 'Chevella', 'Agartala',
       'Bageshwar', 'Ernakulum And Malappuram',
       'Nagpur And Several Districts',
       'Bhopal, Vidhisha, Sehore, Sagar, Hoshangabad, Raisen, Narsinghpur',
       'Orraiya', 'Kargil', 'Jewargi', 'Hanumangarh', 'Budgam', 'Chandel',
       'East Delhi', 'Rampur', 'Shahjahanpur', 'Jaisalmer', 'Kothagudem',
       'Sultanpur', 'Allahabad', 'Nagaur', 'Kishtwar', 'Chittorgarh',
       'Hathras', 'Nayabasti', 'Wahim',
       'Dantewada, Bijapur, Bastar, Sukmaanddhamtari', 'Bundi',
       'Several Districts Anddhalai', 'Darbhanga', 'Koriya', 'Khandwa',
       'Bhubaneshwar', 'West Sikimm', 'Ranjana Sirchilla',
       'Dakshin Dinajpur', 'Varanasi', 'Nilgiris', 'Nawapara',
       'Kangpokpi', 'Nagarkoil', 'Ooty', 'Dhalai', 'Churu', 'Leh',
       'Barmer', 'Karauli', 'Lakshadweep District', 'Kamrup Rural',
       'Mehsana', 'East Imphal West Imphal', 'Badaun', 'Darjeeling',
       'Sarguja', 'Mumbai (City)', 'Etawah', 'North Sikkim',
       'Kavarattii, Minicoy And Amini Island',
       'Minicoy, Amini And Kavaratti Islands', 'Minicoy And Amini Island',
       'All Districts', 'Shahdara', 'Mangalore',
       'Doda, Jammu, Kathua, Kishtwar, Rajouri, Ramban, Reasi, Samba And Udhampur',
       'Ranchi, Palamu, Garwah, Gumla, Chatra, Deoghar, Giridih, Dumka, Lohardaga, Koderma, Jamtara, Ramgarh, Saraikela, Simdega, East Singhbum, Saraikela, Hazaribag, Sahebganj, Bokaro, Latehar, Dhanbad, Ramgarh, West Singhbhum',
       'Ranchi, East Singhbum, Saraikela, Hazaribag, Sahebganj, Bokaro, Latehar, Dhanbad, Ramgarh, West Singhbhum',
       'Papumpare, Lower Subansiri, Upper Subansiri, East Kameng, East Siang, Lohit, Changlang, Kurung Kumey, Upper Siang, West Siang',
       'Papumpare, Lower Subansiri, Upper Subansiri, East Kameng, East Siang, Naharlagun',
       'Bmc, Pune, Nagpur, Latur, Aurangabad Nashik, Kolhapur, Akola And Thane',
       'Papumpare, Lower Subansiri, Upper Subansiri, East Kameng, East Siang',
       'North -West', 'Kozhikode, Mallapuram, Thrissur And Kannur',
       'Cachar, Golaghat Lakhimpur Morigaon', 'Balurghat',
       'West Tripura, South Tripura, Gomati, Sepahijala, Khowai, Dhalai',
       'Garo Hills', 'Midnapore', 'Basti', 'Madukarai', 'Diu', 'Silvassa',
       'East Champaran', 'Central Delhi', 'East Medinapur',
       'Kavarati Island', 'Dhalai And Gomati', 'Gulbarga',
       'North And Middle Andaman', 'Kanyakumari',
       'North, South And Other District',
       'Jaipur Alwar, Dausa, Karauli And Districts', 'North- South',
       'Darjeeling, Jalpaiguri', 'Rohtas, Bhabhua', 'New Delhi',
       'Gomati And Several Districts', 'Rajkot And Several Districts',
       'Kanpur Nagar', 'Berhampur', 'Hisar', 'Rohtak', 'Burwani',
       'Kollegal', 'Kohima And Phek', 'Hubli',
       'Mallapuram, Kasargod, Wayanad, Kozhikode', 'Bulandshahar',
       'Gopalpara', 'Gundlupet', 'Kolkata', 'North Cachar',
       'Barpeta, Nalbari, Jorhat', 'Goa', 'Kobra', 'Kanshi Ram Nagar',
       'Sant Nagar', 'Kotputli', 'Baswara', 'North-East', 'Bhaharatpur',
       'Kasarwad', 'Godavari', 'Ramnad', 'Seppa', 'Chamba',
       'Pratap Nagar', 'Dharamshala', 'Alwar, Sikar, Jaipur', 'Chapra',
       'Narnaul', 'Bakura',
       'Imphal East, Imphal West, Thoubal, Bishnupur And Churachandpur',
       'Badmer', 'Kabri Anglong', 'Dhalai South Tripura',
       'Shillong, East Khasi Hills, West Khasi Hills And Jaintia Hills',
       'Badayun', 'Jaintia Hills And West Kashi Hills',
       'Lahaul And Spiti'], dtype=object)

In [33]:
health['disease_illness_name'].isnull().sum()

np.int64(1)

In [34]:
health['disease_illness_name'].head()

0             Food Poisoning
1            Fever with Rash
2                 Chickenpox
3             Food Poisoning
4    Acute Diarrheal Disease
Name: disease_illness_name, dtype: object

In [35]:
health['disease_illness_name']=health['disease_illness_name'].fillna("Unknown")

In [36]:
health['disease_illness_name'].describe()

count                       26553
unique                        239
top       Acute Diarrheal Disease
freq                         6963
Name: disease_illness_name, dtype: object

In [37]:
health['disease_illness_name'].value_counts()

disease_illness_name
Acute Diarrheal Disease                        6963
Food Poisoning                                 4067
Measles                                        2316
Chickenpox                                     2148
Dengue                                         2116
                                               ...
Viral Fever (Leptospirosis)                       1
Viral Fever (Dengue)                              1
Viral Fever (Leptospirosis and Chikungunya)       1
Rickettsia Scrub Typhus                           1
Food poisoning (Trichinosis)                      1
Name: count, Length: 239, dtype: int64

In [38]:
health['disease_illness_name']=health['disease_illness_name'].str.lower()
health['disease_illness_name']=health['disease_illness_name'].str.title()

In [39]:
health['disease_illness_name'].unique()

array(['Food Poisoning', 'Fever With Rash', 'Chickenpox',
       'Acute Diarrheal Disease', 'Hepatitis A', 'Leishmaniasis',
       'Measles', 'Typhoid', 'Mumps', 'Dengue', 'Human Rabies',
       'West Nile Fever', 'Cholera', 'Scrub Typhus', 'Hmpv', 'Malaria',
       'Mpox', 'Others', 'Hepatitis A And E', 'Acute Gastroenteritis',
       'Fever', 'Meningitis', 'Jaundice', 'Acute Hepatitis A', 'Rabies',
       'Paratyphoid', 'Kannad', 'Acute Gastroentiritis', 'Chikungunya',
       'Khasi', 'Acute Hepatitis E', 'Pertussis', 'Rubella', 'Champaran',
       'Measles And Rubella', 'Hepatitis', 'Gastroenteritis',
       'Nile Fever', 'Poisoning', 'Nagar', 'Hepatitis E',
       'Crimean Congo Haemandrhagic Fever (Cchf)',
       'Japanese Encephalitis', 'Diarrhoea', 'Leptospirosis', 'Kameng',
       'Acute Gastroenteritis (Norovirus)', 'Dengue And Chikungunya',
       'Dysentery', 'Diphtheria', 'Acute Hepatitis', 'Forest Disease',
       'Enteric Fever', 'Zika Virus', 'Nilgiris', 'Unknown', 'Bardhaman',
       'Shigellosis', 'Hand Foot And Mouth Disease',
       'Amoebic Encephalitis', 'Acute Encephalitic Syndrome', 'Paraganas',
       'Nipah Virus', 'Fever Of Unknown Origin', 'Animal Bite - Dog Bite',
       'Poliomyelitis (Vaccine-Derived Polio Virus)', 'Chandipura Virus',
       'Acute Encephalitic Syndrome (Chandipura Virus)',
       'Primary Amoebic Meningo-Encephalitis',
       'Ari Influenza Like Illness(Ili)', 'Only Fever Less Than 7 Days',
       'Mushroom Poisoning', 'Anthrax',
       'Food Poisoning (Mushroom Poisoning)', 'Influenza',
       'Jaundice Of Less Than 4 Weeks', 'Fever Of Unknown Andigin (Puo)',
       'Acute Hepatitis B', 'Suspected Mumps',
       'Suspected Acute Hepatitis', 'Leptospirosis And Scrub Typhus',
       'Kyasanur Fandest Disease', 'Melioidosis', 'Monkey Pox',
       'Fever With Altered Sensandium', 'Tetanus',
       'Dengue And Leptospirosis', 'Brucellosis',
       'Fever Of Unknown Cause', 'Suspected Japanese Encephalitis',
       'Suspected Dengue Fever', 'Suspected Typhoid', 'Acute Gastritis',
       'Animal Bite - Snake Bite', 'Cutaneous Leishmaniasis (Kala Azar)',
       'Suspected Mushroom Poisoning', 'Kala Azar', 'Typhoid Fever',
       'Suspected Human Rabies', 'Acute Diarrheal Disease (Klebsiella)',
       'Suspected Anthrax', 'Dysentery (Shigella)', 'Adenovirus',
       'Acute Flaccid Paralysis', 'Food Poisoning (Shigella Sonnie)',
       'Pyrexia Of Unknown Andigin (Puo)', 'Cutaneous Leishmaniasis',
       'Chickenpox And Measles', 'H3N2', 'Food Poisoning (Nandovirus)',
       'Jatropha Seeds Poisoning',
       'Fever And Upper Respiratandy Tract Infection (Urti)',
       'Allergic Conjunctivitis', 'Fever With Rash (Enterovirus)',
       'Chemical Gas Poisoning', 'Seasonal Influenza',
       'Acute Meningoencephalitis (Naegleria Fowleri)',
       'Swine Flu (H1N1)', 'Malaria And Dengue',
       'Dengue And Scrub Typhus', 'Visceral Leishmaniasis',
       'Acute Respiratandy Illness', 'Nandovirus', 'Filariasis',
       'Influenza A', 'Malaria (Plasmodium Vivax)',
       'Acute Flaccid Paralysis (Epstein Bar Virus And Human Herpes Virus)',
       'Hepatitis B', 'Lyme Disease', 'Acute Febrile Illness',
       'Mixed Fever', 'Hepatitis C', 'Epidemic Dropsy',
       'Acute Respiratandy Infection',
       'Scrub Typhus And Dengue And Leptospirosis', 'Viral Fever',
       'Viral Encephalitis', 'Typhoid (Enteric Fever)',
       'Fever And Dengue', 'Avian Influenza', 'Enteric Fever (Typhoid)',
       'Convulsions Of Unknown Cause', 'Bacillary Dysentery', 'Covid 19',
       'Benzene Hexachlandide (Bhc) Poisoning', 'West Nile And Dengue',
       'Typhoid And Chikungunya', 'Acute Viral Fever',
       'Chikungunya And Leptospirosis', 'Influenza B',
       'Chandipura Vesiculovirus (Chpv)',
       'Hepatitis A And B And Leptospirosis', 'Trypanosomiasis',
       'Food Poisoning (Salmonellosis)',
       'Acute Encephalitis Syndrome (Japanese Encephalitis)',
       'Nipah Viral Disease', 'Food Poisoning (Caster Fruit)',
       'Acute Diarrhoeal Disease (Rota Virus)', 'Salmonellosis',
       'Trichinellosis', 'Uneasiness, Vomiting And Diarrhoea',
       'Fever With Joint Pain', 'Fever With Body Pains',
       'Dengue And Japanese Encephalitis', 'H1N1',
       'Vomiting And Diarrhoea', 'Indigenous Malaria',
       'Acute Viral Encephalitis (Chandipura)', 'Dvd', 'Neonatal Tetanus',
       'Nipah Viral Encephalitis', 'Cutaneous Anthrax', 'Scabies',
       'Seasonal', 'Chickenpox And Mumps', 'Falciparum Malaria',
       'Vivax Malaria', 'Fever And Headache', 'Fever With Arthralgia',
       'Leptospirosis And Typhoid', 'Herpes Simplex Encephalitis',
       'Food Poisoning (Eiec And Shigella)', 'Salmonella Gastroenteritis',
       'Fever With Cough', 'Malaria (Plasmodium Falciparum)',
       'Typhoid, Dengue And Scrub Typhus', 'Measles And Chickenpox',
       'Scrub Typhus And Chikungunya', 'Influenza Like Illness',
       'Hepatitis A And Leptospirosis', 'Food Poisoning (Bamangadh)',
       'Staphylococcal Food Poisoning', 'Acute Viral Conjunctivitis',
       'Food Poisoning (Seed)', 'Acute Respiratandy Influenza',
       'Paederus Dermatitis From Rove Beetle', 'Alcohol Poisoning',
       'Fever (Mixed Infection)', 'Methanol Poisoning',
       'Upper Respiratandy Tract Infection (Urti)',
       'Cast And Seed Poisoning', 'Hepatitis And Jaundice', 'Trichinella',
       'Food Poisoning (Acute Diarrhoeal Disease)',
       'Fever And Chikungunya', 'Acute Febrile Illness And Viral Fever',
       'Acute Diarrhoeal Disease And Respiratandy Tract Infection And Viral Infection',
       'Drug Side Effects', 'Hepatitis B And C', 'Fever Leptospirosis',
       'Acute Febrile Illness And Malaria',
       'Scrub Typhus And Dengue And Chikungunya',
       'Viral Exanthems (Multiple Papulo Pustular Lesions)',
       'Acute Febrile Illness (Enteric Fever)',
       'Malaria And Leptospirosis', 'Viral Infection',
       'Sub Cutaneous Wandm', 'Encephalitis', 'Amoebic Dysentery',
       'Gas Poisoning', 'Vitamin A Overdosage', 'Acute Meningitis',
       'Viral Fever (Dengue And Chikungunya)',
       'Viral Fever (Chikungunya)', 'Food (Alcohol) Poisoning',
       'Food Poisoning (Adverse Effect Following Vitamin A Administration)',
       'Food Poisoning (Staphylococcus)', 'Viral Fever (Leptospirosis)',
       'Meningococcal Meningitis', 'Viral Fever (Dengue)',
       'Viral Fever (Leptospirosis And Chikungunya)',
       'Rickettsia Scrub Typhus', 'Food Poisoning (Trichinosis)'],
      dtype=object)

In [40]:
health['status'].unique()

array(['Reported', 'Reported Late', 'Reported in Same Week',
       'Reported late', 'Reported in same week',
       'Previous Week Follow up', 'Reported During Downtime',
       'Under Survelliance'], dtype=object)

In [41]:
health['status']=health['status'].str.lower()
health['status']=health['status'].str.title()

In [42]:
health['status'].unique()

array(['Reported', 'Reported Late', 'Reported In Same Week',
       'Previous Week Follow Up', 'Reported During Downtime',
       'Under Survelliance'], dtype=object)

In [43]:
health['cases'].describe()

count    26544.000000
mean        62.694545
std        508.280126
min          0.000000
25%         12.000000
50%         21.000000
75%         42.000000
max      51225.000000
Name: cases, dtype: float64

In [44]:
health['cases']=health.groupby("district")['cases'].transform(lambda x:x.fillna(x.median()))

In [45]:
health['cases']=health['cases'].astype(int)

In [46]:
health['deaths']=health.groupby('district')['deaths'].transform('mean')

In [47]:
health['deaths']=health['deaths'].astype(int)

In [48]:
health.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26553 entries, 0 to 26552
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   year                    26553 non-null  int64
 1   week                    26553 non-null  int64
 2   outbreak_starting_date  26546 non-null  datetime64[ns]
 3   reporting_date          18368 non-null  object
 4   state                   26553 non-null  object
 5   district                26553 non-null  object
 6   disease_illness_name    26553 non-null  object
 7   status                  26553 non-null  object
 8   cases                   26553 non-null  int64
 9   deaths                  26553 non-null  int64
dtypes: datetime64[ns](1), int64(4), object(5)
memory usage: 2.0+ MB

In [49]:
health.isnull().sum()

year                         0
week                         0
outbreak_starting_date       7
reporting_date            8185
state                        0
district                     0
disease_illness_name         0
status                       0
cases                        0
deaths                       0
dtype: int64

In [50]:
#health.to_csv("health_clean.csv",index=False)

In [51]:
print(health['outbreak_starting_date'].min(),health['outbreak_starting_date'].max())

2009-05-04 00:00:00 2025-04-05 00:00:00

In [52]:
health['reporting_date'] = pd.to_datetime(
    health['reporting_date'],
    dayfirst=True,
    errors='coerce'
)

In [53]:
print(health['reporting_date'].min(),health['reporting_date'].max())

2009-06-15 00:00:00 2025-04-05 00:00:00

In [54]:
health['state'].value_counts().count()

np.int64(37)

In [55]:
health['state'].value_counts()

state
Maharashtra                                 2679
Karnataka                                   2598
Kerala                                      1963
Tamil Nadu                                  1790
West Bengal                                 1687
Madhya Pradesh                              1623
Bihar                                       1605
Assam                                       1468
Gujarat                                     1441
Uttar Pradesh                               1429
Odisha                                      1380
Jharkhand                                    981
Chhattisgarh                                 871
Andhra Pradesh                               861
Jammu And Kashmir                            660
Rajasthan                                    659
Punjab                                       561
Haryana                                      313
Uttarakhand                                  309
Arunachal Pradesh                            282
Telangana                                    255
Meghalaya                                    196
Himachal Pradesh                             178
Manipur                                      104
Dadra And Nagar Haveli And Daman And Diu      87
Delhi                                         80
Tripura                                       78
Puducherry                                    76
Mizoram                                       74
Nagaland                                      63
Goa                                           55
Chandigarh                                    51
Sikkim                                        37
Unknown                                       35
Lakshadweep                                   11
Andaman And Nicobar Islands                    9
Ladakh                                         4
Name: count, dtype: int64

In [56]:
health['state'].unique()

array(['Assam', 'Bihar', 'Gujarat', 'Haryana', 'Jharkhand', 'Karnataka',
       'Kerala', 'Madhya Pradesh', 'Meghalaya', 'Odisha', 'Puducherry',
       'Tamil Nadu', 'Uttarakhand', 'West Bengal', 'Manipur',
       'Uttar Pradesh', 'Chhattisgarh', 'Jammu And Kashmir',
       'Andhra Pradesh', 'Maharashtra', 'Sikkim', 'Nagaland', 'Punjab',
       'Rajasthan', 'Tripura', 'Mizoram', 'Goa', 'Arunachal Pradesh',
       'Dadra And Nagar Haveli And Daman And Diu', 'Himachal Pradesh',
       'Telangana', 'Andaman And Nicobar Islands', 'Ladakh', 'Chandigarh',
       'Delhi', 'Lakshadweep', 'Unknown'], dtype=object)